name: Main CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip project
        run: zip -r project.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: cs-tap-in-logbucket
          AWS_ACCESS_KEY_ID: "${{ secrets.S3_ACCESS_KEY }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.S3_SECRET_KEY }}"
          SOURCE_DIR: ./
          DEST_DIR: /